name: memoritze
description: A new Flutter project.
publish_to: 'none'
version: 0.18.6

environment:
  sdk: '>=3.0.5 < 4.0.0'

app_installer:
  publish_folder_path

dependencies:
  sqflite_common_ffi: ^2.2.5
  sqflite: ^2.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  share_plus: ^7.0.2
  path_provider: ^2.0.15
  file_picker: ^5.3.3
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  msix: ^3.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/img/

msix_config:
  display_name: Memoritze
  publisher_display_name: SeitCom
  identity_name: Seit.MySuite.mem
  msix_version: 1.1.0.0
  capabilities: " internetClient,privateNetworkClientServer,internetClientServer,enterpriseAuthentication,documentsLibrary,broadFileSystemAccess"
