name: memoritze
description: A new Flutter project.
publish_to: 'none'
version: 0.9.0

environment:
  sdk: '>=3.0.5 < 4.0.0'

app_installer:
  publish_folder_path

dependencies:
  sqflite_common_ffi: any
  sqflite: ^2.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  msix: ^3.14.2

flutter:
  assets:
    - assets/img/
    