name: memoritze
description: A new Flutter project.
publish_to: 'none'
version: 0.9.0

environment:
  sdk: '>=3.0.5 < 4.0.0'

app_installer:
  publish_folder_path

dependencies:
  sqflite_common_ffi: any
  sqflite: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  msix: ^3.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/img/

msix_config:
  display_name: MemoritzeApp
  publisher_display_name: Seita
  identity_name: company.suite.flutterapp
  msix_version: 0.9.0.0
  logo_path: E:\Git\memoritze\memoritze\assets\img\myIcon.png
  capabilities: memory