name: memoritze
description: A new Flutter project.
publish_to: 'none'
version: 0.18.7

environment:
  sdk: '>=3.0.5 < 4.0.0'

app_installer:
  publish_folder_path

dependencies:
  sqflite_common_ffi: ^2.3.0+3
  sqflite: ^2.3.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  share_plus: ^7.2.1
  path_provider: ^2.0.15
  file_picker: ^6.1.1
  provider: ^6.0.5
  mutex: ^3.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/img/
